preload = /home/stoic/.config/hypr/wallpapers/tokyo-tower-night-1920x1080.jpg
preload = /home/stoic/.config/hypr/wallpapers/tokyo-tower-night-alternative-4926x3080.jpg

wallpaper {
	monitor = DP-1
	path = /home/stoic/.config/hypr/wallpapers/tokyo-tower-night-1920x1080.jpg
	fit_mode = cover
}

wallpaper {
	monitor = DP-2
	path = /home/stoic/.config/hypr/wallpapers/tokyo-tower-night-alternative-4926x3080.jpg
	fit_mode = cover
}
